### ISSUE TITLE
Contribution to PyG

### ISSUE THREAD

**Issue by rusty1s** [BUAA-CI-Lab/GNN-Feature-Decomposition#1]
Hi and thank you for this valuable piece of work. This is really interesting.

I'm wondering if you have any plans to contribute this feature directly to PyG? If you are interested, we can layout the details in this issue. One option would be to provide an additional `decompose_edge_level_features()` method inside `torch_geometric.nn.MessagePassing`, which converts message passing modules to directly make use of this feature in a highly modular way. Let me know what you think.

Best,
Matthias

**Comment by ZhouAo-ZA** [comment]
@rusty1s Thank you for your recognition of our work，i also think it is appropriate to add a feature decomposition function in the message passing module，this is very convenient for developers to use this method.

**Comment by rusty1s** [comment]
Great! How shall we proceed with this? One thing that is not yet clear to me is that it looks like one needs to write an additional `decomposed_message` function. It doesn't look like one can re-use `message` easily while decomposing.

**Comment by ZhouAo-ZA** [comment]
I think maybe we can directly add an optional parameter to the `propagate ` function of the `MessagePassing` module to include the feature decomposition process.
When calling the `propagate ` function, the user can choose to enter the feature decomposition layers parameter, like this:
`propagate(...., decomposed_layers=None)`

**Comment by ZhouAo-ZA** [comment]
I think maybe we can directly add an optional parameter to the `propagate ` function of the `MessagePassing` module and rewrite the `propagate ` function to add optional feature decomposition operations.
When calling the `propagate ` function, the user can choose to enter the feature decomposition layers parameter, like this:
`propagate(...., decomposed_layers=None)`.
If you think this is feasible, I can try to modify a sample version, and then we are discussing how to improve the code to make the code as beautiful as possible.

**Comment by rusty1s** [comment]
Sounds great :) Let me know how it goes. Thank you.

**Comment by ZhouAo-ZA** [comment]
@rusty1s I tried to modify an initial version of  `propagate`, and performed a simple test. The added `decomposed_layer` parameter by default will not affect the original logic. The specific modified code is as follows:

Note:  The `decomposed_layer` parameter represents the number of layers to be decomposed. When the default is 1, no feature decomposition is performed. I tried the  GCN inference on CPU, and it can achieve a speedup of 2x - 3x on the Reddit dataset. Our method has better acceleration effect on graphs with higher average node degree.


![image](https://user-images.githubusercontent.com/20035743/132306364-8575efe5-831e-4785-8c1c-3bf8b2de262c.png)

**Comment by rusty1s** [comment]
Awesome. Can you contribute this feature as a PR?

**Comment by ZhouAo-ZA** [comment]
No problem，I will submit it as soon as possible.

**Comment by ZhouAo-ZA** [comment]
I fork the latest master branch, but I found an error when I tried to run the  `/exampls/gcn`. Do you know how to solve it?

![image](https://user-images.githubusercontent.com/20035743/132335309-1d101d6c-45f0-40cd-ac72-6e01ca813849.png)

**Comment by rusty1s** [comment]
You need to delete the processed dataset by removing `root_folder_of_dataset/processed`.

**Comment by ZhouAo-ZA** [comment]
@rusty1s I have seen the code merging, and we have good cooperation. I will close this question，thanks to the efficient GNN framework that the PyG team has brought us. I will continue to conduct research on GNN acceleration and look forward to the next cooperation!
